package com.opensetlist.app

/**
 * Strings de interface do app (pt-BR).
 *
 * @author ruanitto
 */
object AppStrings {
    val appName = "OpenSetlist"
    val splashDevelopedBy = "Desenvolvido por Ruanitto"

    val cancel = "Cancelar"
    val save = "Salvar"
    val ok = "OK"
    val apply = "Aplicar"
    val pickDate = "Escolher data e hora"
    val delete = "Excluir"
    val create = "Criar"
    val close = "Fechar"
    val name = "Nome"
    val back = "Voltar"
    val menu = "Menu"

    val allSongsTitle = "Todas as Músicas"
    val setlistsTitle = "Set Lists"
    val artistsTitle = "Artistas"
    val tagsTitle = "Tags"
    val settingsTitle = "Configurações"
    val aboutTitle = "Sobre"
    val aboutDescription = "OpenSetlist é um gerenciador de músicas e setlists para músicos. Organize seu repertório com cifras em ChordPro, monte roteiros de apresentação e compartilhe tudo em formato .osl."
    val aboutDevelopedBy = "Desenvolvido com amor ❤\uFE0F por Rafael Gomes"
    val editSongTitle = "Editar Música"

    val searchSongsPlaceholder = "Buscar músicas e setlists..."
    val searchSetlistsPlaceholder = "Buscar setlist por nome ou local..."
    val searchArtistsPlaceholder = "Buscar artistas..."
    val searchTagsPlaceholder = "Buscar tags..."
    val searchInSongPlaceholder = "Buscar no texto..."
    val searchSongsToAddPlaceholder = "Buscar músicas..."
    val setlistsHeader = "SETLISTS"
    val songsHeader = "MÚSICAS"

    val noSetlistsYet = "Nenhuma setlist ainda"
    val noSetlistsFound = "Nenhuma setlist encontrada"
    val emptySetlist = "Setlist vazia"
    val dragToReorderHint = "Toque e arraste para reordenar as músicas."
    val allSongsInSetlist = "Todas as músicas já estão nesta setlist."
    val noArtists = "Nenhum artista cadastrado"
    val noTags = "Nenhuma tag cadastrada"
    val noSongsOfArtist = "Nenhuma música deste artista"
    val noSongsWithTag = "Nenhuma música com esta tag"
    val noSongsFound = "Nenhuma música encontrada"

    val titleLabel = "Título"
    val artistLabel = "Artista"
    val keyLabel = "Tom"
    val bpmLabel = "BPM"
    val capoLabel = "Capo"
    val transposeLabel = "Transpor"
    val durationLabel = "Duração"
    val compassoLabel = "Compasso"
    val youtubeLinkLabel = "Link do YouTube"
    val bodyLabel = "Letra / Cifra (ChordPro)"
    val metadataTab = "Metadados"
    val chordProTab = "Texto ChordPro"

    val durationPlaceholder = "3:45"
    val compassoPlaceholder = "4/4"
    val youtubePlaceholder = "https://youtube.com/watch?v=..."
    val datePlaceholder = "ex.: 12/05/2026"
    val locationPlaceholder = "ex.: Bar do Zé"
    val timePlaceholder = "ex.: 20:30"
    val dateLabel = "Data"
    val locationLabel = "Local"
    val timeLabel = "Horário"
    val newTagPlaceholder = "Nova tag"

    val newSong = "Nova música"
    val newSetlist = "Nova setlist"
    val newArtist = "Novo artista"
    val newTag = "Nova tag"
    val addSong = "Adicionar música"
    val addSongs = "Adicionar músicas"
    val editSetlist = "Editar setlist"
    val editArtist = "Editar artista"
    val editTag = "Editar tag"
    val editGigInfo = "Editar dados da Gig"
    val renameSetlist = "Renomear setlist"
    val renameArtist = "Renomear artista"
    val renameTag = "Renomear tag"
    val deleteSetlist = "Excluir setlist"
    val deleteSong = "Excluir música"
    val deleteArtist = "Excluir artista"
    val deleteTag = "Excluir tag"
    val shareSetlist = "Compartilhar setlist"
    val reorder = "Reordenar"
    val removeFromSetlist = "Remover da setlist"
    val addTag = "Adicionar tag"
    val importPro = "Importar .pro"
    val exportPro = "Exportar .pro"
    val search = "Buscar"
    val edit = "Editar"
    val moreOptions = "Mais opções"
    val viewOnYoutube = "Ver no YouTube"
    val previous = "Anterior"
    val next = "Próximo"
    val transposeMinusOne = "Transpor -1"
    val transposePlusOne = "Transpor +1"
    val decreaseFont = "Diminuir letra"
    val increaseFont = "Aumentar letra"
    val showChords = "Mostrar acordes"
    val hideChords = "Ocultar acordes"
    val autoScroll = "Rolagem automática"
    val pedalBluetooth = "Pedal Bluetooth"
    val speedLabel = "Velocidade:"
    val decreaseSpeed = "Diminuir velocidade"
    val increaseSpeed = "Aumentar velocidade"

    val sortNameAsc = "Nome (A-Z)"
    val sortNameDesc = "Nome (Z-A)"
    val sortArtistAsc = "Artista (A-Z)"
    val sortArtistDesc = "Artista (Z-A)"
    val sortCreatedAsc = "Criação (antigas)"
    val sortCreatedDesc = "Criação (recentes)"
    val sortLocationAsc = "Local (A-Z)"
    val sortLocationDesc = "Local (Z-A)"
    val sortDateAsc = "Data (crescente)"
    val sortDateDesc = "Data (decrescente)"
    val sortSongsAsc = "Menos músicas"
    val sortSongsDesc = "Mais músicas"

    val restoreBackup = "Restaurar backup"
    val restoreBackupConfirm = "Isso substituirá todos os dados atuais pelos dados do backup. Continuar?"
    val restore = "Restaurar"

    val backupDbTitle = "Backup do banco de dados"
    val exportFullBackup = "Exportar backup completo (.db)"
    val exportFullBackupSubtitle = "Copia o banco SQLite inteiro, pronto para uso externo"
    val importBackup = "Importar backup (.db)"
    val importBackupSubtitle = "Restaura todos os dados a partir de um arquivo .db"
    val cloudTitle = "Nuvem"
    val cloudSyncSubtitle = "Escolha Google Drive ou Dropbox no seletor do sistema"
    val syncTitle = "Sincronizar"
    val appearanceTitle = "Aparência"
    val darkMode = "Modo escuro"
    val keepScreenOnTitle = "Manter tela acesa"
    val keepScreenOnViewer = "Visualização de música"
    val keepScreenOnPlaylist = "Playlist"
    val keepScreenOnAlways = "O tempo todo"
    val googleDrive = "Google Drive"
    val dropbox = "Dropbox"
    val exportToGoogleDrive = "Exportar para Google Drive"
    val importFromGoogleDrive = "Importar do Google Drive"
    val exportToDropbox = "Exportar para Dropbox"
    val importFromDropbox = "Importar do Dropbox"
    val exportCloudBackup = "Exportar backup para a nuvem"
    val importCloudBackup = "Importar backup da nuvem"
    val songsSectionTitle = "Músicas"
    val exportAllSongs = "Exportar todas as músicas"
    val importSongsBatch = "Importar músicas (em lote)"
    val setlistHelperTitle = "SetList Helper"
    val importSetlistHelper = "Importar backup do SetList Helper"
    val importSetlistHelperSubtitle = "Restaura músicas e setlists de um backup .db"
    val importSharedSetlist = "Importar setlist compartilhada"

    val importSong = "Importar música"
    val fromInternet = "Da internet"
    val onlineSearchTitle = "Buscar cifras na internet"
    val onlineSearchPlaceholder = "Ex.: Artista - Música · ou cole uma URL"
    val onlineSearchAction = "Buscar"
    val cifraClubSource = "Cifra Club"
    val ultimateGuitarSource = "Ultimate Guitar"
    val googleSource = "Buscar no Google"
    val searchRunning = "Buscando..."
    val onlineSearchFailed = "Falha ao buscar. Verifique sua conexão e tente de novo."
    val noCifraFound = "Nenhuma cifra encontrada"
    val openInEditor = "Abrir no editor"
    val importChordSheet = "Importar"
    val composerLabel = "Composição"
    val tuningLabel = "Afinação"
    val copiedFromInternet = "Importada da internet"
    val openSongInBrowser = "Abrir no navegador"

    val justChordsTitle = "JustChords"
    val importJustChords = "Importar setlist JustChords (.chopro/.jcarchive)"
    val importJustChordsSubtitle = "Importa setlist exportada do app JustChords"
    val justChordsImportFailed = "Falha ao importar setlist JustChords"
    val restoreBackupLogTitle = "Restauração de backup"
    val importSongsLogTitle = "Importação de músicas"
    val importSetLogTitle = "Importação de setlist"
    val importSetlistHelperLogTitle = "Importação do SetList Helper"
    val importJustChordsLogTitle = "Importação do JustChords"
    val shareFormatTitle = "Compartilhar como"
    val justChordsFormat = "JustChords (.chopro)"
    val justChordsArchiveFormat = "JustChords (.jcarchive)"
    val opensetlistFormat = "OpenSetList (.osl)"

    val saveBackupToFile = "Salvar backup em arquivo"
    val shareBackup = "Compartilhar backup"
    val importBackupFile = "Importar backup"
    val saveSongsToFile = "Salvar todas em .pro (um por música)"
    val shareSongs = "Compartilhar todas (.osl)"
    val importSongs = "Importar músicas"
    val importSetlistHelperFile = "Importar backup do SetList Helper"
    val importSetlist = "Importar setlist"

    val fileSaved = "Arquivo salvo"
    val fileSaveFailed = "Falha ao salvar arquivo"
    val contentShared = "Conteúdo compartilhado"
    val noSongsToExport = "Nenhuma música para exportar"
    val exportProgressTitle = "Exportar músicas"
    val importLogSuccess = "Importação concluída com sucesso"
    fun logStarting(title: String) = "Iniciando $title..."
    fun logSongImported(title: String) = "Importada: $title"
    fun logSetlistImported(name: String) = "Setlist: $name"
    fun logRestoreSummary(songCount: Int, setCount: Int) =
        "Backup com $songCount música(s) e $setCount setlist(s)"
    fun proExportStarting(count: Int) = "Iniciando exportação de $count música(s) em .pro"
    val proExportWaitingFolder = "Aguardando escolha da pasta de destino..."
    fun proExportSongStarted(title: String) = "Iniciada: $title"
    fun proExportSongDone(title: String) = "Concluída: $title"
    fun proExportSongFailed(title: String) = "Falhou: $title"
    fun proExportCompleted(seconds: String, saved: Int, failed: Int) =
        if (failed > 0) "Exportação concluída em $seconds — $saved salva(s), $failed falha(s)"
        else "Exportação concluída em $seconds"
    val proExportCancelled = "Exportação cancelada"
    val proExportRunning = "Exportando..."
    val proExportFinished = "Concluído"
    val proExportClose = "Concluir"
    val cancelExport = "Cancelar exportação"
    val cancelExportDialogTitle = "Cancelar exportação?"
    val cancelExportDialogMessage = "A exportação será interrompida. Deseja continuar?"
    val invalidBackupFile = "Arquivo de backup inválido"
    val invalidSongsFile = "Arquivo de músicas inválido"
    val invalidSetlistFile = "Arquivo de setlist inválido"
    val invalidDbFile = "Arquivo .db inválido ou não é um backup deste app"
    val dbReadFailed = "Falha ao ler o banco de dados"
    val backupRestored = "Backup restaurado com sucesso"
    val invalidOrEmptyBackup = "Backup inválido ou vazio"
    val slhImportFailed = "Falha ao importar backup do SetList Helper"

    val untitledSong = "Música sem título"
    val unknownArtist = "Artista desconhecido"
    val newSongTitle = "Nova música"
    val defaultArtistName = "Artista"
    val importedSetlistName = "Setlist importada"

    val deleteConfirmation = "Excluir \"%s\"?"
    val deleteArtistWithSongs = "Excluir também as %d músicas deste artista"

    val durationUnitHour = "h"
    val durationUnitMinute = "min"
    val durationUnitSecond = "s"

    val metaTom = "Tom"
    val metaTempo = "Tempo"
    val metaCompasso = "Compasso"
    val metaDuracao = "Duração"
    val metaCapo = "Capo"
    val metaCompositor = "Compositor"
    val metaLetra = "Letra"
    val metaAlbum = "Álbum"
    val metaAno = "Ano"
    val metaTags = "Tags"

    fun editSongTitle(name: String) = "Editar $name"
    fun songsCount(count: Int) = "$count músicas"
    fun setlistsCount(count: Int) = "$count setlists"
    fun artistsCount(count: Int) = "$count artistas"
    fun tagsCount(count: Int) = "$count tags"
    fun songsImported(count: Int) = "$count músicas importadas"
    fun setlistImported(name: String) = "Setlist \"$name\" importada"
    fun slhImported(songCount: Int, setCount: Int) =
        "Importadas $songCount músicas e $setCount setlists do SetList Helper"
    fun justChordsImported(songCount: Int, setCount: Int) =
        "Importadas $songCount músicas e $setCount setlist(s) do JustChords"
    fun metaKeyValue(label: String, value: String) = "$label: $value"
}
